image: "fedora:26"

before_script:
        - dnf -y install which gcc-c++ make cmake
              boost-devel
              boost-filesystem
              boost-system
              boost-regex
              boost-date-time
              boost-iostreams
              popt-devel
              zlib-devel
              readline-devel
              postgresql-devel
              sqlite-devel
              gettext
              gettext-libs
              libzstd
              libzstd-devel

pg_backup_ctl-plus:
        script:
                - mkdir build
                - cd build
                - CXXFLAGS="-D __DEBUG__" cmake ..
                - make
