# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bernd/git/pg_backup_ctl++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bernd/git/pg_backup_ctl++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bernd/git/pg_backup_ctl++/CMakeFiles /Users/bernd/git/pg_backup_ctl++/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bernd/git/pg_backup_ctl++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pgbckctl-common

# Build rule for target.
pgbckctl-common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pgbckctl-common
.PHONY : pgbckctl-common

# fast build rule for target.
pgbckctl-common/fast:
	$(MAKE) -f CMakeFiles/pgbckctl-common.dir/build.make CMakeFiles/pgbckctl-common.dir/build
.PHONY : pgbckctl-common/fast

#=============================================================================
# Target rules for targets named pg_backup_ctl++

# Build rule for target.
pg_backup_ctl++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pg_backup_ctl++
.PHONY : pg_backup_ctl++

# fast build rule for target.
pg_backup_ctl++/fast:
	$(MAKE) -f CMakeFiles/pg_backup_ctl++.dir/build.make CMakeFiles/pg_backup_ctl++.dir/build
.PHONY : pg_backup_ctl++/fast

src/main/common.o: src/main/common.cxx.o

.PHONY : src/main/common.o

# target to build an object file
src/main/common.cxx.o:
	$(MAKE) -f CMakeFiles/pgbckctl-common.dir/build.make CMakeFiles/pgbckctl-common.dir/src/main/common.cxx.o
.PHONY : src/main/common.cxx.o

src/main/common.i: src/main/common.cxx.i

.PHONY : src/main/common.i

# target to preprocess a source file
src/main/common.cxx.i:
	$(MAKE) -f CMakeFiles/pgbckctl-common.dir/build.make CMakeFiles/pgbckctl-common.dir/src/main/common.cxx.i
.PHONY : src/main/common.cxx.i

src/main/common.s: src/main/common.cxx.s

.PHONY : src/main/common.s

# target to generate assembly for a file
src/main/common.cxx.s:
	$(MAKE) -f CMakeFiles/pgbckctl-common.dir/build.make CMakeFiles/pgbckctl-common.dir/src/main/common.cxx.s
.PHONY : src/main/common.cxx.s

src/main/pg_backup_ctl.o: src/main/pg_backup_ctl.cxx.o

.PHONY : src/main/pg_backup_ctl.o

# target to build an object file
src/main/pg_backup_ctl.cxx.o:
	$(MAKE) -f CMakeFiles/pg_backup_ctl++.dir/build.make CMakeFiles/pg_backup_ctl++.dir/src/main/pg_backup_ctl.cxx.o
.PHONY : src/main/pg_backup_ctl.cxx.o

src/main/pg_backup_ctl.i: src/main/pg_backup_ctl.cxx.i

.PHONY : src/main/pg_backup_ctl.i

# target to preprocess a source file
src/main/pg_backup_ctl.cxx.i:
	$(MAKE) -f CMakeFiles/pg_backup_ctl++.dir/build.make CMakeFiles/pg_backup_ctl++.dir/src/main/pg_backup_ctl.cxx.i
.PHONY : src/main/pg_backup_ctl.cxx.i

src/main/pg_backup_ctl.s: src/main/pg_backup_ctl.cxx.s

.PHONY : src/main/pg_backup_ctl.s

# target to generate assembly for a file
src/main/pg_backup_ctl.cxx.s:
	$(MAKE) -f CMakeFiles/pg_backup_ctl++.dir/build.make CMakeFiles/pg_backup_ctl++.dir/src/main/pg_backup_ctl.cxx.s
.PHONY : src/main/pg_backup_ctl.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... pgbckctl-common"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pg_backup_ctl++"
	@echo "... src/main/common.o"
	@echo "... src/main/common.i"
	@echo "... src/main/common.s"
	@echo "... src/main/pg_backup_ctl.o"
	@echo "... src/main/pg_backup_ctl.i"
	@echo "... src/main/pg_backup_ctl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

